#!/bin/bash

SRCFILE=./
DEST="/etc/ansible/roles"

# Create the file structure in /etc/ansible/roles
mkdir -p $DEST/{'install-elk'/{files,tasks},'install-filebeat'/{files,tasks},'install-metricbeat'/{files,tasks}}

# Elk files
mv $SRCFILE/install-elk.yml -P $DEST/install-elk/tasks/

# Filebeat files
mv $SRCFILE/install-filebeat.yml -P $DEST/install-filebeat/tasks/
mv $SRCFILE/filebeat-config.yml -P $DEST/install-filebeat/files/

# Metricbeat files
mv $SRCFILE/install-metricbeat.yml -P $DEST/install-metricbeat/tasks/
mv $SRCFILE/metricbeat-config.yml -P $DEST/install-metricbeat/files/
